version: '3.8'

services:
  cepm-vp-api:
    build: .  # Builds from the Dockerfile in the same dir
    container_name: cepm-vp-api
    restart: unless-stopped
    ports:
      - "12980:12980"
    labels:
      - "com.datadoghq.ad.logs: '[{\"source\": \"nodejs\", \"service\": \"cepm-vp-api\", \"env\":\"prod\"}]'"
    environment:
      DD_ENABLED: true
      DD_VERSION: 004
      DD_ENV: prod
      DD_SERVICE: cepm-api
      LDAP_URL: ${LDAP_URL}
      LDAP_SEARCH_BASE: ${LDAP_SEARCH_BASE}
      LDAP_SEARCH_FILTER: ${LDAP_SEARCH_FILTER}
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN_PREPEND: ${DOMAIN_PREPEND}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_DATABASE: ${DB_DATABASE}
      DB_USE_UTC: ${DB_USE_UTC}
      DB_POOL_MIN: ${DB_POOL_MIN}
      DB_POOL_MAX: ${DB_POOL_MAX}
      DB_POOL_IDLE_TIMEOUT: ${DB_POOL_IDLE_TIMEOUT}
    networks:
      - tracing-net

# Optional: Add this for faster rebuilds on updates
volumes:
  cepm_data:
networks:
  tracing-net:
    external: true
